name: bbclub-font
brand: bbclub-font
description: bb stands for baseball. Icon font set that contains baseball club logos.
keyword: 
url: http://daigofuji.github.io/bbclub-font/
email : daigo@daigofujiwara.com
author: Daigo Fujiwara